Fix spawn on Windows
On Windows (in GitHub Actions test environment) the `create` script
failed because the spawn raised ENOENT:

        Error: spawn npm ENOENT

Using the shell should fix this.