Pin Heroku to v10 in tests
These tests (most recently re-introduced in #1636) are designed to ensure that the Prototype Kit works on Heroku.

They use the `heroku local` command to run the kit locally whilst trying to mimic what Heroku does in production. The `heroku local` command is run via npx which automatically installs the latest version of `heroku`.

Heroku recently shipped v11 of `heroku`, and the tests are now running against v11.0.2 and failing with:

```
Error: ENOENT: no such file or directory, open 'Procfile'
    Code: ENOENT
```

It looks like `heroku local` used to support running against projects that do not have a Procfile, but this broke in v11 (https://github.com/heroku/cli/issues/3630).

Given prototypes don’t have a Procfile, I’ve raised #2520 to investigate whether these tests are useful or valuable.

In the meantime, as the tests are currently failing on main, pin heroku to v10 to unblock other work.