Update node-sass to v4.14.1
v4.12.0 does not support Node v14:

> Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (83)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v4.13.1
>     at module.exports (/Users/oliverbyford/Code/govuk-prototype-kit/node_modules/node-sass/lib/binding.js:13:13)
>     at Object.<anonymous> (/Users/oliverbyford/Code/govuk-prototype-kit/node_modules/node-sass/lib/index.js:14:35)
>     at Module._compile (internal/modules/cjs/loader.js:1200:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
>     at Module.load (internal/modules/cjs/loader.js:1049:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:937:14)
>     at Module.require (internal/modules/cjs/loader.js:1089:19)
>     at require (internal/modules/cjs/helpers.js:73:18)
>     at Object.<anonymous> (/Users/oliverbyford/Code/govuk-prototype-kit/node_modules/gulp-sass/index.js:162:21)
>     at Module._compile (internal/modules/cjs/loader.js:1200:30)
> gulp exited with code 1